version: '2.0'

services:
  node1.onezone:
    image: onedata/onezone:17.06.0-rc5
    hostname: node1.onezone.
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: onezone-1
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistance
        - "${ONEZONE_CONFIG_DIR}:/volumes/persistence"
        # OpenId configuration
        #- "${AUTH_PATH}:/var/lib/oz_worker/auth.config"
        # DNS configuration
        #- "${DNS_PATH}:/var/lib/oz_worker/dns.config"
        # Onepanel
        #- "${OZ_PRIV_KEY_PATH}:/etc/oz_panel/certs/key.pem"
        #- "${OZ_CERT_PATH}:/etc/oz_panel/certs/cert.pem"
        #- "${OZ_CACERT_PATH}:/etc/oz_panel/cacerts/cacert.pem"
        #- "${OZ_CACERT_PATH}:/etc/oz_worker/cacerts/cacert.pem"
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "80:80"
      - "5555:5555"
      - "5556:5556"
      - "6665:6665"
      - "6666:6666"
      - "7443:7443"
      - "8443:8443"
      - "8876:8876"
      - "8877:8877"
      - "9443:9443"
    environment:
      # Used for test purposes, disable when you have your own web cert mounted via volumes.
      # Cert will be generated only if none is found under cert path.
      ONEPANEL_AUTOGENERATE_CERT: "true"
      # The auto-generated web cert will be issued for below domain.
      ONEPANEL_AUTOGENERATED_CERT_DOMAIN: "node1.onezone"
